WITH RECURSIVE TEMP AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT a.ID, a.PARENT_ID, (GENERATION + 1) AS GENERATION
    FROM ECOLI_DATA a
    JOIN TEMP b ON a.PARENT_ID = b.ID
)
SELECT COUNT(*) AS COUNT, GENERATION AS GENERATION
FROM TEMP
WHERE ID NOT IN (SELECT DISTINCT(PARENT_ID) FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
GROUP BY GENERATION
ORDER BY 2 ASC;