WITH TOTAL AS (
    SELECT COUNT(*) AS TOTAL
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
INFOS AS (
SELECT a.YEAR AS YEAR, a.MONTH AS MONTH, a.USER_ID
FROM (
    SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, USER_ID
    FROM ONLINE_SALE
) a
JOIN (
    SELECT USER_ID AS USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
) b
ON a.USER_ID = b.USER_ID
)
SELECT MAX(YEAR) AS YEAR, MAX(MONTH) AS MONTH, COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, ROUND(COUNT(DISTINCT USER_ID) / (SELECT TOTAL FROM TOTAL), 1) AS PURCHASED_RATIO
FROM INFOS
GROUP BY YEAR, MONTH
ORDER BY 1 ASC, 2 ASC;