SELECT a.ID AS ID, a.GENOTYPE AS GENOTYPE, b.GENOTYPE AS PARENT_GENOTYPE
FROM (SELECT ID, PARENT_ID, GENOTYPE FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL) a
JOIN ECOLI_DATA b
ON a.PARENT_ID = b.ID
WHERE a.GENOTYPE & b.GENOTYPE = b.GENOTYPE
ORDER BY 1 ASC;