SELECT YEAR(a.DIFFERENTIATION_DATE) AS YEAR, b.SIZE - a.SIZE_OF_COLONY AS YEAR_DEV, a.ID AS ID
FROM ECOLI_DATA a
JOIN (SELECT MAX(YEAR(DIFFERENTIATION_DATE)) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE FROM ECOLI_DATA GROUP BY YEAR(DIFFERENTIATION_DATE)) b
ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY 1 ASC, 2 ASC;