SELECT a.SCORE AS SCORE, b.EMP_NO AS EMP_NO, b.EMP_NAME AS EMP_NAME, b.POSITION AS POSITION, b.EMAIL AS EMAIL
FROM (SELECT MAX(EMP_NO) AS EMP_NO, SUM(SCORE) AS SCORE FROM HR_GRADE WHERE YEAR = 2022 GROUP BY EMP_NO ORDER BY 2 DESC LIMIT 1) a
JOIN HR_EMPLOYEES b ON a.EMP_NO = b.EMP_NO;