SELECT ALGORITHM_TYPE AS ALGORITHM_TYPE
FROM (
    SELECT MAX(ALGORITHM_TYPE) AS ALGORITHM_TYPE, COUNT(*) AS COUNT
    FROM PROBLEMS
    GROUP BY ALGORITHM_TYPE
    ORDER BY 2 DESC, 1 ASC
) a
LIMIT 1;