WITH TEMP AS (
    SELECT CASE WHEN a.SUBMITTED = b.CORRECT_ANSWER THEN 1 ELSE 0 END AS CORRECT_COUNT,
            ROW_NUMBER() OVER (PARTITION BY a.USER_ID, a.PROBLEM_ID ORDER BY TIMESTAMP ASC) AS RN
    FROM SUBMISSIONS a
    JOIN PROBLEMS b
    ON a.PROBLEM_ID = b.PROBLEM_ID
),
TEMP2 AS (
    SELECT MAX(RN) AS NTH_SUBMISSION, SUM(CORRECT_COUNT) AS CORRECT_COUNT, COUNT(*) AS TOTAL_COUNT
    FROM TEMP a
    GROUP BY RN
)
SELECT NTH_SUBMISSION, ROUND(CORRECT_COUNT / TOTAL_COUNT * 100) AS CORRECT_RATE
FROM TEMP2
ORDER BY 1 ASC;