WITH CORRECT AS (
    SELECT a.USER_ID AS USER_ID, a.PROBLEM_ID AS PROBLEM_ID, a.TIMESTAMP AS TIMESTAMP, b.SCORE AS SCORE, 
            ROW_NUMBER () OVER (PARTITION BY a.USER_ID, PROBLEM_ID ORDER BY TIMESTAMP ASC) AS RN
    FROM SUBMISSIONS a
    JOIN PROBLEMS b
    ON a.PROBLEM_ID = b.PROBLEM_ID AND a.SUBMITTED = b.CORRECT_ANSWER
),
FIRST_CORRECT AS (
    SELECT USER_ID AS USER_ID, PROBLEM_ID, SCORE, TIMESTAMP
    FROM CORRECT
    WHERE RN = 1
),
LAST_CORRECT AS (
    SELECT MAX(USER_ID) AS USER_ID, MAX(TIMESTAMP) AS TIMESTAMP
    FROM FIRST_CORRECT
    GROUP BY USER_ID
),
PENALTY AS (
    SELECT a.USER_ID AS USER_ID,
            a.TIMESTAMP AS TIMESTAMP
    FROM LAST_CORRECT a
    JOIN SUBMISSION b
    ON a.USER_ID = b.USER_ID AND a.PROBLEM_ID = b.PROBLEM_ID AND a.TIMESTAMP > b.TIMESTAMP
)
SELECT MAX(a.USER_ID) AS USER_ID, SUM(IFNULL(b.SCORE, 0)) AS TOTAL_SCORE
FROM (SELECT DISTINCT USER_ID FROM SUBMISSIONS) a
LEFT JOIN FIRST_CORRECT b
ON a.USER_ID = b.USER_ID
GROUP BY a.USER_ID
ORDER BY 2 DESC, 1 ASC;