SELECT a.ID, IFNULL(b.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA a
LEFT JOIN (SELECT MAX(PARENT_ID) AS PARENT_ID, COUNT(*) AS COUNT FROM ECOLI_DATA GROUP BY PARENT_ID) b
ON a.ID = b.PARENT_ID
ORDER BY 1 ASC;