SELECT a.ID AS ID, b.FISH_NAME AS FISH_NAME, a.LENGTH AS LENGTH
FROM (
    SELECT a.ID AS ID, a.FISH_TYPE AS FISH_TYPE, a.LENGTH AS LENGTH
    FROM FISH_INFO a
    JOIN (SELECT MAX(FISH_TYPE) AS FISH_TYPE, MAX(LENGTH) AS LENGTH FROM FISH_INFO GROUP BY FISH_TYPE) b
    ON a.FISH_TYPE = b.FISH_TYPE AND a.LENGTH = b.LENGTH
) a
JOIN FISH_NAME_INFO b
ON a.FISH_TYPE = b.FISH_TYPE
ORDER BY 1 ASC;