SELECT a.DEPT_ID AS DEPT_ID, b.DEPT_NAME_EN AS DEPT_NAME_EN, a.AVG_SAL AS AVG_SAL
FROM (SELECT MAX(DEPT_ID) AS DEPT_ID, ROUND(AVG(SAL)) AS AVG_SAL FROM HR_EMPLOYEES GROUP BY DEPT_ID) a
JOIN HR_DEPARTMENT b
ON a.DEPT_ID = b.DEPT_ID
ORDER BY 3 DESC;