SELECT a.ITEM_ID AS ITEM_ID, b.ITEM_NAME AS ITEM_NAME, b.RARITY AS RARITY
FROM (
    SELECT a.ITEM_ID
    FROM ITEM_TREE a
    LEFT JOIN ITEM_TREE b 
    ON a.ITEM_ID = b.PARENT_ITEM_ID
    WHERE b.ITEM_ID IS NULL
) a
JOIN ITEM_INFO b
ON a.ITEM_ID = b.ITEM_ID
ORDER BY 1 DESC;