SELECT a.PRODUCT_ID AS PRODUCT_ID, b.PRODUCT_NAME AS PRODUCT_NAME, a.TOTAL_AMOUNT * b.PRICE AS TOTAL_SALES
FROM (
    SELECT MAX(PRODUCT_ID) AS PRODUCT_ID, SUM(AMOUNT) AS TOTAL_AMOUNT
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
    GROUP BY PRODUCT_ID
) a
JOIN FOOD_PRODUCT b
ON a.PRODUCT_ID = b.PRODUCT_ID
ORDER BY 3 DESC, 1 ASC;