SELECT DISTINCT(b.ID) AS ID, b.EMAIL AS EMAIL, b.FIRST_NAME AS FIRST_NAME, b.LAST_NAME AS LAST_NAME
FROM (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) a
JOIN DEVELOPERS b
ON a.CODE & b.SKILL_CODE
WHERE a.CODE & b.SKILL_CODE
ORDER BY 1 ASC;