SELECT b.MEMBER_NAME AS MEMBER_NAME, a.REVIEW_TEXT AS REVIEW_TEXT, DATE_FORMAT(a.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM (
    SELECT MEMBER_ID, REVIEW_TEXT, REVIEW_DATE
    FROM REST_REVIEW
    WHERE MEMBER_ID = (
        SELECT MAX(MEMBER_ID) FROM REST_REVIEW GROUP BY MEMBER_ID ORDER BY COUNT(*) DESC LIMIT 1
    )
) a
JOIN MEMBER_PROFILE b
ON a.MEMBER_ID = b.MEMBER_ID
ORDER BY 3 ASC, 2 ASC;