SELECT 
    MAX(YEAR(b.SALES_DATE)) AS YEAR, 
    MAX(MONTH(b.SALES_DATE)) AS MONTH,
    MAX(a.GENDER) AS GENDER,
    COUNT(DISTINCT b.USER_ID) AS USERS
FROM (
    SELECT *
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
) a
JOIN ONLINE_SALE b
ON a.USER_ID = b.USER_ID
GROUP BY YEAR(b.SALES_DATE), MONTH(b.SALES_DATE), a.GENDER
ORDER BY 1 ASC, 2 ASC, 3 ASC;