SELECT a.REST_ID AS REST_ID, 
    a.REST_NAME AS REST_NAME, 
    a.FOOD_TYPE AS FOOD_TYPE, 
    a.FAVORITES AS FAVORITES, 
    a.ADDRESS AS ADDRESS, 
    IFNULL(b.SCORE, 0) AS SCORE
FROM (SELECT * FROM REST_INFO WHERE ADDRESS LIKE '서울%') a
JOIN (
    SELECT MAX(REST_ID) AS REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
    FROM REST_REVIEW
    GROUP BY REST_ID
) b
ON a.REST_ID = b.REST_ID
ORDER BY 6 DESC, 4 DESC;