SELECT a.CATEGORY AS CATEGORY, a.PRICE AS MAX_PRICE, a.PRODUCT_NAME AS PRODUCT_NAME
FROM (
    SELECT CATEGORY, PRICE, PRODUCT_NAME, ROW_NUMBER () OVER (partition by CATEGORY order by PRICE DESC) AS RN 
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
) a
WHERE a.RN = 1
ORDER BY 2 DESC;