WITH TEMP AS (SELECT ID, EMAIL, SKILL_CODE,
    (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AS Python, 
    (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') AS CSharp, 
    (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS Front
FROM DEVELOPERS),
TEMP2 AS (SELECT CASE
        WHEN (SKILL_CODE & Python) AND (SKILL_CODE & Front) THEN 'A'
        WHEN SKILL_CODE & CSharp THEN 'B'
        WHEN SKILL_CODE & Front THEN 'C'
        ELSE NULL END AS GRADE, ID, EMAIL
FROM TEMP)
SELECT GRADE, ID, EMAIL
FROM TEMP2
WHERE GRADE IS NOT NULL
ORDER BY 1 ASC, 2 ASC;