SELECT DATE_FORMAT(a.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, a.PRODUCT_ID, a.USER_ID, a.SALES_AMOUNT
FROM (
    (SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    WHERE SALES_DATE BETWEEN '2022-03-01' and '2022-03-31')
    UNION
    (SELECT SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT
    FROM OFFLINE_SALE
    WHERE SALES_DATE BETWEEN '2022-03-01' and '2022-03-31')
) a
ORDER BY 1 ASC, 2 ASC, 3 ASC;
