SELECT CART_ID AS CART_ID
FROM (
    SELECT MAX(CART_ID) AS CART_ID, 
            SUM(CASE WHEN NAME = 'Milk' THEN 1 ELSE 0 END) AS MILK_COUNT,
            SUM(CASE WHEN NAME = 'Yogurt' THEN 1 ELSE 0 END) AS YOGURT_COUNT
    FROM CART_PRODUCTS
    WHERE NAME IN ('Milk', 'Yogurt')
    GROUP BY CART_ID
) a
WHERE a.MILK_COUNT > 0 AND a.YOGURT_COUNT > 0
ORDER BY 1 ASC;