WITH RECURSIVE HOUR_CTE AS (
    SELECT 0 as HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOUR_CTE
    WHERE HOUR < 23
)
SELECT a.HOUR AS HOUR, IFNULL(b.COUNT, 0) AS COUNT
FROM HOUR_CTE a
LEFT JOIN (
    SELECT MAX(HOUR(DATETIME)) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
) b
ON a.HOUR = b.HOUR
ORDER BY 1 ASC
