WITH TEMP AS (
    SELECT HISTORY_ID,
            CAR_ID,
            DATEDIFF(END_DATE, START_DATE) + 1 AS DAYS,
            CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
                WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
                ELSE 'NO DISCOUNT' END AS DURATION
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_TYPE = '트럭'
    )
)
SELECT a.HISTORY_ID, ROUND(a.DAYS * b.DAILY_FEE * (1 - IFNULL(c.DISCOUNT_RATE, 0) / 100)) AS FEE
FROM TEMP a
JOIN CAR_RENTAL_COMPANY_CAR b
ON a.CAR_ID = b.CAR_ID
LEFT JOIN (
    SELECT DURATION_TYPE, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭'
) c
ON a.DURATION = c.DURATION_TYPE
ORDER BY 2 DESC, 1 DESC;