SELECT 
    MAX(b.AUTHOR_ID) AS AUTHOR_ID, 
    MAX(c.AUTHOR_NAME) AS AUTHOR_NAME,
    MAX(b.CATEGORY) AS CATEGORY,
    SUM(a.SALES * b.PRICE) AS TOTAL_SALES
FROM (
    SELECT MAX(BOOK_ID) AS BOOK_ID, SUM(SALES) AS SALES
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
) a
JOIN BOOK b
ON a.BOOK_ID = b.BOOK_ID
JOIN AUTHOR c
ON b.AUTHOR_ID = c.AUTHOR_ID
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY 1 ASC, 3 DESC;