SELECT a.APNT_NO AS APNT_NO, b.PT_NAME AS PT_NAME, a.PT_NO AS PT_NO, a.MCDP_CD AS MCDP_CD, c.DR_NAME AS DR_NAME, a.APNT_YMD AS APNT_YMD
FROM (
    SELECT APNT_NO, PT_NO, MCDP_CD, MDDR_ID, APNT_YMD 
    FROM APPOINTMENT 
    WHERE APNT_CNCL_YN = 'N' 
    AND APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59' 
    AND MCDP_CD = 'CS'
) a
JOIN PATIENT b
ON a.PT_NO = b.PT_NO
JOIN DOCTOR c
ON a.MDDR_ID = c.DR_ID
ORDER BY 6 ASC