-- 세단과 SUV 차 ID 리스트
WITH SU AS (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE IN ('세단', 'SUV')
),
-- 대여가 불가능한 차 ID 리스트
IMP AS (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE CAR_ID IN (SELECT CAR_ID FROM SU) AND START_DATE <= '2022-11-30' AND  END_DATE >= '2022-11-01'
)
SELECT a.CAR_ID, a.CAR_TYPE, ROUND(30 * a.DAILY_FEE * (1 - b.DISCOUNT_RATE / 100)) AS FEE
FROM SU a
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN b
ON a.CAR_TYPE = b.CAR_TYPE AND b.DURATION_TYPE = '30일 이상'
WHERE a.CAR_ID NOT IN (SELECT CAR_ID FROM IMP) AND (30 * a.DAILY_FEE * (1 - b.DISCOUNT_RATE / 100)) >= 500000 AND (30 * a.DAILY_FEE * (1 - b.DISCOUNT_RATE / 100)) < 2000000
ORDER BY 3 DESC, 2 ASC, 1 DESC;